### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by Darth45013** [happyzleaf/PokexpMultiplier#1]
keeps saying was not a valid sub command on every command i try even /pokexp info

**Comment by hqppyz** [comment]
What happens if you use this build instead (for 5.0.2 and 5.0.3)?
(please extract the zip, github didn't let me upload the jar)
[pokexpmultiplier-1.1.2.zip](https://github.com/happyzleaf/PokexpMultiplier/files/891279/pokexpmultiplier-1.1.2.zip)

**Comment by hqppyz** [comment]
I'm gonna close this due to the inactivity of @Darth45013, but this should be fixed
