### ISSUE TITLE
[support]Pixemon6.3.1 support ~~~~

### ISSUE THREAD

**Issue by PorPit** [happyzleaf/PokexpMultiplier#10]
Pixemon6.3.1 was  uptodate
but the PokexpMultiplier has some err in battle
can u support the new version?
https://reforged.gg/

**Comment by hqppyz** [comment]
Already got some logs for that, which version of PokexpMultiplier are you using?

**Comment by hqppyz** [comment]
Also, the error log must be attached to the issue

**Comment by hqppyz** [comment]
Closing, the 6.3.2 does not need an update, if there are any other problems open a new issue or refer to them in an existing one.
