### ISSUE TITLE
Rare candy leveling up Pokemon twice

### ISSUE THREAD

**Issue by SnowBlitzz** [happyzleaf/PokexpMultiplier#11]
In Pixelmon 7.0.5 it seems like when the xp multiplier is at x2, using a rare candy will level up the Pokemon twice. Don't think that's intended, but if it's intended, I think there should be a way to not have them work on rare candies.

**Comment by vaniron** [comment]
To be more specific i does not level up pokemon twice, just give him double the xp needed for next level. Basicly plugin does not care where is the experience coming from, all is multiplied.

**Comment by hqppyz** [comment]
I doubt I have any way to prevent that, I'll take a look at the pixelmon source and if anything's on their side you'll have to wait for the next release.
But no clue right now, I can't touch anything till next week

**Comment by hqppyz** [comment]
Okay so I modified my fork of the pixelmon, and I updated the plugin. As soon as it gets accepted into master I'm gonna push the update, then when it's gonna be released I can push the new update,
