### ISSUE TITLE
color codes aren't working in game

### ISSUE THREAD

**Issue by MrBringBacon** [happyzleaf/PokexpMultiplier#13]
I have it set to the default and it seems like it should appear in a blue color, yet in game it's just all white. Was wondering if I did something wrong? honestly I didn't even mess with the config but who knows.

**Comment by hqppyz** [comment]
Show your config.

**Comment by MrBringBacon** [comment]
https://pastebin.com/MZjzWhhL
https://gyazo.com/acb40952e0b918c6228643323039a5c3
