### ISSUE TITLE
Plugin isn't responding to commands!

### ISSUE THREAD

**Issue by zerafox** [happyzleaf/PokexpMultiplier#14]
**forge-1.12.2-14.23.5.2844**
**spongeforge-1.12.2-2838-7.1.7-RC3950**

The following commands aren't doing a thing for me.

/pokexp _(Not enough arguments)_
/pokexp info _(unknown command)_

There are no errors, I've tried with an untouched configuration file.
It's always the same result.

**Comment by hqppyz** [comment]
You could try `/pokexpmultiplier:pokexp info <player>`, it has always been working.
If it still won't work, try to see if there are errors in the log.

**Comment by zerafox** [comment]
I did try the command like this, and no there were not errors in the log.
However this is now 2 months old and I have given up on using the plugin that did not work for me at all in the first place.
So to say "it has always been working" is funny, because it never once worked for me. No matter what I tried.

For the record, this isn't my first rodeo. If there were errors, or anything I could give you. I would've.
Sadly this was so broken for me, it gave me literally nothing.

**Comment by hqppyz** [comment]
Well I haven't received any other issues related to that and other peeps are using it.
Unfortunately I'm not able to do anything at the moment, I'm under an hard uni session.
I'll try to get back and update everything after this period. If I forget you can ping me.

**Comment by zerafox** [comment]
Admittingly this was 3/4 months ago now, and for it to not have worked within that time frame I've since dropped it completely.
So try to fix it, don't try to fix it.. At this point it doesn't matter any to me since I've given up trying to use it.
