### ISSUE TITLE
placeholder crash

### ISSUE THREAD

**Issue by vaniron** [happyzleaf/PokexpMultiplier#2]
Hello,
found server crashing if placeholderapi is installed - i dont even use pixelmon variables in scoreboard. Can something be done about this? I tried multiple placeholderapi version without any success.
Crashlog: https://pastebin.com/raw/ZaJWkxVM

**Comment by hqppyz** [comment]
The best thing i can do is to update it to PlaceholderAPI 4.4
Can you test this build and see if it works for you? 'Cause i can't reproduce your error
[pokexpmultiplier-1.1.5.zip](https://github.com/happyzleaf/PokexpMultiplier/releases)

**Comment by vaniron** [comment]
Yup, looks like working. Thanks for updating.

**Comment by hqppyz** [comment]
Closing
