### ISSUE TITLE
Boss errors

### ISSUE THREAD

**Issue by PixelmonPRO** [happyzleaf/PokexpMultiplier#3]
When you kill bosses, write the following: https://gist.github.com/PixelmonPRO/1f0ff843e79ebfb0b92d437807c41b54
Forge: `2587` / SpongeForge: `2833` / Pixelmon: `6.1.0` / Plugin: `1.1.6`
Config: https://gist.github.com/PixelmonPRO/08cc3d4023a86a5ba7312e33f145fba1

**Comment by hqppyz** [comment]
Does this happen always or just with an algorithm? Can you test it without Hiroku's Tournaments?

**Comment by PixelmonPRO** [comment]
Very strange - but the error disappeared by itself (without removing the plugin)
