### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by vaniron** [happyzleaf/PokexpMultiplier#4]
Server crashing after player tossing pokeball in drop table (after battle) menu. Unfortunately cant force players do not use drop GUI but its connected with pokexpmultiplier.

Log: https://pastebin.com/raw/KJkGptVQ
Version: sponge 5 - 1.10.2

**Comment by vaniron** [comment]
Update: Its not related to drops - its problem with eggs and exp all in party. This sidemod tries to add xp even to the egg, but it crashes the server. Without sidemod, everything is ok.

**Comment by hqppyz** [comment]
Will fix within the next update

**Comment by hqppyz** [comment]
Hello! After quite a long time i've finally found the time to come and fix this plugin.
I'm trying to fix all the issues but the crash log is old and i'm not sure where some messages are pointing at, so i'm here to ask for your help, i need you to test my plugin with the version attached below, and to comment here with all the info that could help me find the problem(s), be sure to attach your config and whatever thing could have changed the behaviour of the battle, like if a player used any kind of weird held item or anything like that.
Download PokexpMultiplier 1.1.7 [here](https://mega.nz/#!WwRyDaBJ!_JH9uP16VYXrXXYZ9tLpkononMdf493YSngKcl9NPZI).
Note that the bug could still be there even if nothing weird appeared in the console! So be sure to see if you've got the experience and such!

(message copy pasted to all the issues)

**Comment by hqppyz** [comment]
Fixed in 1.1.8
