### ISSUE TITLE
Caught error in battle

### ISSUE THREAD

**Issue by 0Fox** [happyzleaf/PokexpMultiplier#7]
https://pastebin.com/raw/kkuFyygd

Pixelmon Reforged 6.2.2 latest patch
Sponge  1.12.2-2611-7.1.0-BETA-2970

**Comment by hqppyz** [comment]
Hello! After quite a long time i've finally found the time to come and fix this plugin.
I'm trying to fix all the issues but the crash log is old and i'm not sure where some messages are pointing at, so i'm here to ask for your help, i need you to test my plugin with the version attached below, and to comment here with all the info that could help me find the problem(s), be sure to attach your config and whatever thing could have changed the behaviour of the battle, like if a player used any kind of weird held item or anything like that.
Download PokexpMultiplier 1.1.7 [here](https://mega.nz/#!WwRyDaBJ!_JH9uP16VYXrXXYZ9tLpkononMdf493YSngKcl9NPZI).
Note that the bug could still be there even if nothing weird appeared in the console! So be sure to see if you've got the experience and such!

(message copy pasted to all the issues)

**Comment by 0Fox** [comment]
Looks like issue was Reforged 6.2.2, in 6.2.3 all works fine with no errors from this plugin.

**Comment by SnowBlitzz** [comment]
https://pastebin.com/ZE4C4cUY

still happening

**Comment by 0Fox** [comment]
Ok, I manage to find save file of user pokemons who has this issue 100% of time.
https://mega.nz/#!QM5S0C5Q!i95Yi1IoXm2DRYjuqvroQehQaOPO3ztuq6aAWokepTc
I cant debug what causes null pointer because my IntelliJ refuses to import pixelmon as lib..

**Comment by SnowBlitzz** [comment]
It's not player-specific. It only happens if they have an item on their pokemon that also modified exp such as an exp share, lucky egg or exp all.

**Comment by hqppyz** [comment]
alright, i'll take a look

**Comment by hqppyz** [comment]
It looks to be fixed with the latest 1.1.8, the download will be available very soon.
![](https://i.imgur.com/cecOqUO.png)
