### ISSUE TITLE
Instant lvl 100

### ISSUE THREAD

**Issue by SnowBlitzz** [happyzleaf/PokexpMultiplier#8]
Got a report from a player (There are several actually but this sums it up):

> So this all happened accidentally and was never intentional. So I was wondering and tping people to pokeloot just cause I felt like it and while doing this I encountered a wild tedyursa and I killed it exept not really it had lived on 0 health then I decided to catch it and a message came telling me to report the glitch to a pixelmon administrator. So I just blew it off as a weird glitch. But then I decided to continue tping people to pokeloot. During this I encountered another wild pokemon charmander and I caught it this is when the glitch began. It started spamming "you caught a wild charmander" and "Your pidgeot has gained (number) exp" then after my pokemon reached lvl 100 it just kept on sending me those messages. I tried doing /endbattle it told me battle ended but the interface was still there and I couldn't move then I treid /endbattle again and its said "you are not in a battle". I told some mods in discord and they told me it was probly a visual glitch I rejoined and my pokemon was lvl 100 and I caught the charmander.. I don't know if those 2 glitches corespoded but who knows. Heres the part where it could spam chat, if it had just so happened that the charmander was shiny it would keep repeating "(name) has caught a shiny charmander"

This is on 1.1.7 version (unreleased/beta)

**Comment by hqppyz** [comment]
Uhg, i'm pretty sure i won't be able to reproduce it, and to fix it. I'm not sure if it's my plugin's fault, next time it happens try to catch the errors in the log, if any.

**Comment by SnowBlitzz** [comment]
It only ever happens when the multiplier is turned on but ok.

**Comment by hqppyz** [comment]
I did not explain correctly, i didn't mean it was not caused by my plugin, i meant that i was not sure if it was my plugin's fault, cause there could be bad entities which my plugin could try to get some info from, causing problems, but not strictly because of my plugin.
Anyway, it seems not to be the source of the problems, i was just pointing out things

**Comment by hqppyz** [comment]
The issue is probably fixed, i've closed all the other issues but i'll keep this open just so you can test it and tell me how it goes

**Comment by hqppyz** [comment]
The issue seems to be fixed, you can open this issue again if you're experiencing problems
